backend:
  name: github
  repo: ClydeCreator/aurora-tcg-site
  branch: main
  auth_scope: repo

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "cards"
    label: "Cartes TCG"
    folder: "content/cards"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
