backend:
  name: github
  repo: ClydeCreator/aurora-tcg-site
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/uploads" # Dossier où seront stockées les images
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey" # Remplace par ta vraie clé si tu utilises Uploadcare

collections:
  - name: "cards"
    label: "Cartes TCG"
    folder: "content/cards"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
